version: '3'
services:
  dhis2:
    image: blsq/dhis2:${DHIS2_VERSION}
    restart: always
    env_file: .env
    volumes:
      - dhis2_files:/root/files
    expose:
      - "8080"
    ports:
      - 8080:8080
    networks: 
      - proxy
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
{% if TLS_ENABLED %}  
      - 'traefik.http.routers.dhis2.entrypoints=websecure'
      - 'traefik.http.routers.dhis2.middlewares=no-auth-secured@file'
      - 'traefik.http.routers.dhis2.rule=Host(`${DHIS2_DOMAIN_NAME}`)'
      - 'traefik.http.routers.dhis2.tls.certresolver=lets-encrypt'
      - 'traefik.http.routers.dhis2.tls.options=mintls12@file'
{% else %}
      - 'traefik.http.routers.dhis2.entrypoints=web'
      - 'traefik.http.routers.dhis2.middlewares=no-auth-secured@file'
      - 'traefik.http.routers.dhis2.rule=Host(`${DHIS2_DOMAIN_NAME}`)'
{% endif %}
      - "traefik.http.services.dhis2.loadbalancer.passhostheader=true"
networks:
  proxy:
    external: true  
volumes:
  dhis2_files: