---
- name: Install dependencies for PostgreSQL
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - acl
    - openssl
    - libssl-dev
    - libssl-doc
    - gnupg
    - curl

- name: Ensure locales exist                                                                                                                                                                                                                                              
  locale_gen:                                                                                                                                                                                                                                                             
    name: 'en_US.UTF-8'                                                                                                                                                                                                                                                    
    state: present  

- name: Import the repository signing key
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present  

- name: Add PostgreSQL repository
  shell: echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee  /etc/apt/sources.list.d/pgdg.list
  
- name: Update system
  shell: apt update

- name: "Install PostgreSQL"
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - postgresql-{{DHIS2_POSTGRES_VERSION}}
    - libpq-dev
    - python3-psycopg2
    - postgresql-{{DHIS2_POSTGRES_VERSION}}-postgis-3  