---
- hosts: dhis2
  become: yes

  tasks:
    - name: install pip3
      apt: name=python3-pip state=present update-cache=yes 

    - name: Install latest passlib with pip
      pip: name=passlib  
 
    - name: Configure locale to 'en_US.UTF-'
      command: localectl set-locale LANG={{ config_system_locale }}

- hosts: dhis2
  become: yes
  roles:
      - ../roles/docker-compose-systemd
  vars:
      docker_services:
      - name: dhis2
        enabled: yes
        need_restart: yes
        root_dir: /srv/docker/dhis2
        compose_template: docker/dhis2/docker-compose.yml
        env_template: docker/.env
        unit_template: docker-compose/compose-unit.j2

    