---
- name: "create directory for project"
  file:
    path: "{{ item.root_dir }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ docker_services }}"
- name: "deploy systemd service"
  template:
    src: "{{ item.unit_template }}"
    dest: "/etc/systemd/system/{{ item.name}}.service"
    force: true
  register: service
  with_items:
    - "{{ docker_services }}"

- name: "deploy docker compose"
  template:
    src: "{{ item.compose_template }}"
    dest: "{{ item.root_dir}}/docker-compose.yml"
    force: true
  register: compose
  with_items:
    - "{{ docker_services }}"

- name: "deploy docker compose env file"
  template:
    src: "{{ item.env_template }}"
    dest: "{{ item.root_dir}}/.env"
    force: true
  register: env
  with_items:
    - "{{ docker_services }}"    

- name: "Autostart?"
  systemd:
    enabled: "{{ item.enabled | default('yes') }}"
    daemon_reload: yes
    name: "{{ item.name }}"
  with_items:
    - "{{ docker_services }}"

- name: "Do we need to restart service with changed docker compose/systemd unit file?"
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item.item.name }}"
  when: need_restart == True and item.changed
  vars:
    info: "{{ item.item|default({}) }}"
    need_restart: "{{ info.need_restart|default('False') }}"

  with_items:
    - "{{ compose.results }}"
    - "{{ env.results }}"
    - "{{ service.results }}"
  loop_control:
    label: "{{ item.item.name }}; changed = {{ item.changed }}; reason: need restart = {{ need_restart }}"
